# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-11 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='A person with no name apparently', max_length=80)),
                ('lname', models.CharField(default='A person with no name apparently', max_length=80)),
                ('email', models.CharField(default='Seriously, no email? it is 2019 get with it man', max_length=80)),
                ('password', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
